language: php

php:
  - '7.0'
  - '7.1'
  
before_script:
  - composer self-update
  - composer --version
  - composer require adamb/database --no-update

script: composer install --prefer-dist --no-interaction